# Generated by Django 4.1.7 on 2023-04-23 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0003_alter_food_id_alter_postfood_id_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('calorie_count', models.FloatField(default=0)),
                ('calorie_goal', models.PositiveIntegerField(default=0)),
                ('foods_selected', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calories.profile')),
            ],
        ),
    ]
