# Generated by Django 4.2.4 on 2023-08-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0005_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
        migrations.DeleteModel(
            name='ProfileReport',
        ),
    ]
